/**
 * Level 5-2 "Gallery of Color": the Curator's favorite exhibits are frozen cats on display.
 * Security lasers (Z) sweep the halls; touching one hurts and sets off the alarm. Shoot the
 * emitters to switch them off. Legend: see level17.js.
 */
export const level18 = {
  id: '5-2',
  title: 'Gallery of Color',
  place: 'Pale · The Great Gallery',
  theme: 'vault',
  beaconName: 'Gallery Beacon',
  map: [
    '####################################',
    '#S.......#.......c.......#.......*.#',
    '#........#...............#.........#',
    '#...c....#....Z.....Z....#...c.....#',
    '#........#...............#.........#',
    '#..............B...B...............#',
    '#####..#####.........#####..########',
    '#.........R.....J.....R.......a....#',
    '#...Z......................Z......V#',
    '#.........R...........R............#',
    '#..a..........P...P................#',
    '#....c....................c........#',
    '#####...####.......####....#########',
    '#.....d....#...Z...#......#........#',
    '#..V.......#.......#..a...#...J....#',
    '#..........#...c...#......#........#',
    '#..................................#',
    '#...h.....B.........B.....#WWWWWWWW#',
    '#.........................#........#',
    '#.*....Z..................#...E....#',
    '#.........................#........#',
    '#...d.......a.......*.....#........#',
    '#.........................#........#',
    '####################################',
  ],
  stages: [{ tasks: ['rescue', 'vats'] }],
  rescueLabel: 'Free the frozen exhibits',
  rescueSpeaker: 'Exhibit',
  vatPattern: ['archivist', 'drab', 'drab', 'stencil', 'fizz', 'drab'],
  defendPool: ['drab', 'drab', 'drab', 'archivist', 'archivist', 'fizz', 'stencil', 'mopper'],
  beaconChargeTime: 32,
  lines: {
    intro: [
      ['Nova', 'Cats. On pedestals. With little name plaques.'],
      ['Smudge', 'Beep… (it reads one: “Townscat, Purrville, common”)'],
      ['Nova', 'Okay, now I’m angry. Watch the red lasers, Smudge.'],
    ],
    stolen: [['Nova', 'Give that back!']],
    rescue_1: [['Exhibit', 'Is it… is it over? Did someone finally come?']],
    rescue_6: [['Nova', 'Every exhibit is free. Nobody belongs in a jar, or on a pedestal.']],
    vats_1: [['Nova', 'One Vat down!']],
    stageClear: [['Nova', 'Exhibits freed, Vats popped. The Gallery Beacon is open, southeast!']],
    beaconStart: [['Nova', 'Gallery Beacon, light it up!'], ['Smudge', 'BEEP! (alarm! alarm!)']],
    lowHealth: [['Smudge', 'Beep! (H for sardines, B for bubbles!)']],
    beaconDone: [['Nova', 'Now THAT is a gallery.']],
  },
};
