/** Level 2-2 "The Sunken Lab": pre-Bleach ruins. Read the four murals, pop the Vats. Legend: see level5.js / level1.js. */
export const level6 = {
  id: '2-2',
  title: 'The Sunken Lab',
  place: 'Glowshroom Jungle · Ancient Ruins',
  theme: 'ruins',
  beaconName: 'Lab Beacon',
  map: [
    '####################################',
    '#S......#######...........#######.*#',
    '#.......#######.....U.....#######..#',
    '#..N.......R.......d.......R....z..#',
    '#..........................f.......#',
    '#....R.....~~~~~~.....R.......V....#',
    '#.........M~~..~~M.................#',
    '#####.....#~~.U~~#.....d.....#######',
    '#####.....#~~M.~~#....z......#######',
    '#.....h....~~~~~~.....R......R.....#',
    '#....z.............................#',
    '#..R.......R.......R.......R.......#',
    '#.....f........................m...#',
    '###########......###########....####',
    '#U........#......#.........#....*..#',
    '#.....d...#......#....V....#.......#',
    '#..*......................#WWWWWWWW#',
    '#.....z...#.....U.........#........#',
    '#..........R..............#...E....#',
    '#....f.......d......R.....#........#',
    '#.........................#........#',
    '####################################',
  ],
  stages: [{ tasks: ['murals', 'vats'] }],
  vatPattern: ['smear', 'drab', 'fizz', 'smear', 'mopper', 'drab'],
  beaconChargeTime: 30,
  npcs: [
    {
      id: 'moss', name: 'Professor Moss', model: 'moss',
      lines: [
        ['Professor Moss', 'Careful, young courier! These ruins are older than the Bleach itself.'],
        ['Professor Moss', 'Those murals tell what happened here. Read all four and you’ll understand our grey visitors.'],
        ['Professor Moss', 'Here, for your trouble. And mind the pools; the old bounce mushrooms still work.'],
      ],
      reward: { items: { bomb: 2, shield: 1 } }, rewardText: '+2 Paint Bombs, +1 Bubble Shield',
      after: [['Professor Moss', 'Walk up to a mural and press E to read it.']],
    },
  ],
  lines: {
    intro: [
      ['Nova', "A lab… down here? Who builds a lab in a jungle?"],
      ['Smudge', 'Beep. (it scans the walls, very interested)'],
    ],
    murals_1: [['Nova', 'They drew Chroma from the Prism Heart…']],
    murals_4: [['Nova', '"Never let the color run out." So that’s where the Curator came from.']],
    vats_1: [['Nova', 'One Vat down!']],
    stageClear: [['Nova', 'Murals read, Vats popped. The Lab Beacon is open, southeast!']],
    beaconStart: [['Nova', 'Come on, old beacon. One more time.'], ['Smudge', 'Beep-beep! (they are coming!)']],
    lowHealth: [['Smudge', 'Beep! (H for sardines, B for bubbles!)']],
    beaconDone: [['Nova', 'The ruins remember their colors.']],
  },
};
