/**
 * Level 4-2 "Static Storm": surges of static roll across the Wastes, closing the view
 * and bringing Statics. Tune the four radio towers to calm the storm. Legend: see level13.js.
 */
export const level14 = {
  id: '4-2',
  title: 'Static Storm',
  place: 'The Static Wastes · Signal Flats',
  theme: 'wastes',
  beaconName: 'Signal Beacon',
  map: [
    '####################################',
    '#S......####..........####........*#',
    '#..N....####....n.....####....A....#',
    '#...................B..............#',
    '#...A.......P...........n.....B....#',
    '#..........~~~~~~::~~~~~~..........#',
    '####......~~..........~~......######',
    '#.........~~...####...~~...........#',
    '#....n....::...####...::....d...V..#',
    '#.........~~..........~~...........#',
    '#...B.....~~~~~~::~~~~~~.....R.....#',
    '#......h...........................#',
    '#..R...........n.......B......n....#',
    '#.......####...........####........#',
    '#..V....####....A......####...h....#',
    '#..................................#',
    '#....n.......B.......n......P......#',
    '#.........~~~~~~~~~::~~~~~~~~~.....#',
    '#..A......~~.................~~....#',
    '#.........~~..t.....d.......~~WWWWW#',
    '#....P....::................~~.....#',
    '#.........~~.....*..........~~..E..#',
    '#*........~~~~~~~~~~~~~~~~~~~~.....#',
    '####################################',
  ],
  storm: { first: 9, every: [16, 22], dur: 7, spawn: 3 },
  stages: [{ tasks: ['towers', 'vats'] }],
  vatPattern: ['static', 'drab', 'drab', 'static', 'stencil', 'mopper'],
  defendPool: ['drab', 'drab', 'drab', 'static', 'static', 'fizz', 'mopper'],
  beaconChargeTime: 30,
  npcs: [
    {
      id: 'dot', name: 'Dot', model: 'dot',
      lines: [
        ['Dot', 'Kssht! Is this thing on? Courier! You can hear me? Great, ’cause nobody else can. The storm eats every signal.'],
        ['Dot', 'Four old radio towers out here. Tune them and the static calms right down. Clean signal pops those noisy ghosts, too.'],
        ['Dot', 'When a surge rolls in you won’t see past your whiskers. Stay close to a tower, or stay moving. Here, take these.'],
      ],
      reward: { items: { shield: 1, bomb: 1 } }, rewardText: '+1 Bubble Shield, +1 Paint Bomb',
      after: [['Dot', 'Static surge coming? Find something to put your back against.']],
    },
  ],
  lines: {
    intro: [
      ['Nova', 'Why is the sky… buzzing?'],
      ['Smudge', 'Bzzzt! (it shakes its antenna)'],
    ],
    surge: [['Smudge', 'BZZT! (static surge! cannot see!)'], ['Nova', 'Stay close, Smudge. Tune the towers and this stops.']],
    towers_1: [['Nova', 'One tower tuned. The static backed off!']],
    towers_3: [['Smudge', 'Beep! (one tower left!)']],
    towers_4: [['Nova', 'All four towers! Listen… quiet.']],
    vats_1: [['Nova', 'One Vat down!']],
    stageClear: [['Nova', 'Towers tuned, Vats popped. The Signal Beacon is open, southeast!']],
    beaconStart: [['Nova', 'Signal Beacon, broadcast some color!'], ['Smudge', 'BEEP! (here they come!)']],
    lowHealth: [['Smudge', 'Beep! (H for sardines, B for bubbles!)']],
    beaconDone: [['Nova', 'Coming through loud and clear.']],
  },
};
