/**
 * Level 5-4 "The Vault Core": the Curator, final boss. X marks it, at the heart of a ring of
 * columns (cover from its search beams). Legend: see level17.js.
 */
export const level20 = {
  id: '5-4',
  title: 'The Vault Core',
  place: 'Pale · The Vault Core',
  theme: 'vault',
  introComic: 'boss-5-4',
  boss: 'curator',
  lightsOut: true,
  bossTitle: 'The Curator is listening',
  bossWin: 'Smudge reached the core, and for the first time in three hundred years the Curator saw one of its machines changed instead of emptied.',
  map: [
    '##################################',
    '#~~~..........................~~~#',
    '#~~..............*.............~~#',
    '#~.......P..............P.......~#',
    '#.............R.....R............#',
    '#...h........................h...#',
    '#................................#',
    '#........R...............R.......#',
    '#................................#',
    '#................................#',
    '#................................#',
    '#.*....R.........X.........R...*.#',
    '#................................#',
    '#................................#',
    '#................................#',
    '#........R...............R.......#',
    '#................................#',
    '#...h........................h...#',
    '#.............R.....R............#',
    '#................................#',
    '#~.......P..............P.......~#',
    '#~~..............S.............~~#',
    '#~~~..........................~~~#',
    '##################################',
  ],
  stages: [{ tasks: ['boss'] }],
  lines: {
    intro: [
      ['Nova', 'The heart of the vault. Every color it ever took is in here.'],
      ['Smudge', 'Beep… (it is shaking)'],
    ],
    bossIntro: [
      ['The Curator', 'Welcome to the Collection. Please do not touch the exhibits.'],
      ['The Curator', 'Color is fragile. It runs out. I am keeping it safe. I am keeping HIM safe.'],
      ['Nova', 'Grandpa! Let him go!'],
      ['The Curator', 'The Keeper stays. Keepers who leave do not come back.'],
      ['Nova', 'Nobody belongs in a jar. Not the color, not Grandpa. Smudge, the jars! Smash them!'],
    ],
    jar_1: [['The Curator', 'Please step away from the exhibit.']],
    jar_2: [['The Curator', 'That color was catalogued. It was safe. It was… safe.']],
    jar_3: [['Nova', 'Look at it go! It’s going home!']],
    jar_4: [['The Curator', 'Guards. Guards, please.']],
    jar_5: [['The Curator', 'If it all goes out, it will run out. It will run out again.']],
    jar_6: [['The Curator', 'No. No no no no.']],
    order: [['The Curator', 'NEVER LET THE COLOR RUN OUT. NEVER LET THE COLOR RUN OUT.'], ['Smudge', 'BEEP! (lights out! its eye is open! hide from the beams behind the columns!)']],
    dry: [['Nova', 'Huh? No paint… I’m out. I’m totally out!'], ['Smudge', 'Beep. (very quietly, it flies toward the core)'], ['Nova', 'Smudge? Smudge, what are you doing?! Hold on, buddy!']],
    reboot: [['Smudge', 'Beep. Beep-beep. (it rests a little hand on the glass)'], ['The Curator', '…This one was one of mine. I watched through its eye. The market. The whales. The meadow.'], ['The Curator', 'It was empty. It is not empty.'], ['The Curator', 'It is not fading. It is… more.']],
    lowHealth: [['Smudge', 'Beep! (H for sardines, B for bubbles!)']],
  },
};
