/** Level 1-3 "Festival Square": thaw the frozen townscats and relight the Festival Beacon in the middle of the square. Legend: see level1.js. */
export const level3 = {
  id: '1-3',
  title: 'Festival Square',
  place: 'Purrville · Festival Square',
  theme: 'festival',
  beaconName: 'Festival Beacon',
  map: [
    '####################################',
    '#S...#######..........#######....c.#',
    '#....#######...Q..Q...#######......#',
    '#..........................d.......#',
    '#...c....P......f.......P.......V..#',
    '####...######........######...######',
    '#......######.WWWWWW.######........#',
    '#..d...######.W....W.######....c...#',
    '#.............W..E.W...............#',
    '#...Q.....P...W....W...P.....Q.....#',
    '#.........*...WWWWWW......m........#',
    '#.c......f.......................h.#',
    '####....#######.......#######..#####',
    '#N......#######...c...#######......#',
    '#.......#######.......#######..*...#',
    '#..V....Q....Q....Q....Q....c......#',
    '#..........................f.......#',
    '#....P......d.......P........m.....#',
    '#..*.....##########..........B.....#',
    '#........##########.....c.........w#',
    '#.................L................#',
    '####################################',
  ],
  stages: [{ tasks: ['rescue', 'vats'] }],
  vatPattern: ['drab', 'fizz', 'drab', 'mopper', 'drab', 'drab', 'fizz', 'mopper'],
  beaconChargeTime: 30,
  weaponCase: 'hose',
  npcs: [
    {
      id: 'tom', name: 'Old Tom', model: 'tom',
      lines: [
        ['Old Tom', "Festival's ruined, kid. Half the town's frozen solid in the square."],
        ['Old Tom', 'Stand close to a frozen cat and your warm courier heart will thaw them out. Here, take this.'],
      ],
      reward: { sparks: 25, items: { shield: 1 } }, rewardText: '+25 Sparks, +1 Bubble Shield',
      after: [['Old Tom', 'Press B for a Bubble Shield when it gets hairy.']],
    },
  ],
  lines: {
    intro: [
      ['Nova', 'Festival Square… it was the brightest place in town.'],
      ['Nova', 'Thaw everyone, pop the Vats, relight the Festival Beacon. Let\'s go.'],
    ],
    rescue_1: [['Nova', "You're okay! Get somewhere safe!"]],
    rescue_4: [['Smudge', 'Beep-beep! (three more on the minimap)']],
    vats_1: [['Nova', 'One Vat down!']],
    stageClear: [
      ['Nova', 'Everyone is thawed and the Vats are gone. The beacon cage is open!'],
    ],
    beaconStart: [
      ['Nova', 'Festival Beacon, light it up!'],
      ['Smudge', 'BEEEEP! (that is a lot of robots)'],
    ],
    lowHealth: [['Smudge', 'Beep! (H for sardines, B for bubbles!)']],
    beaconDone: [['Nova', 'Happy festival, Purrville.']],
  },
};
