/** Level 1-2 "Tram Yards": restart four generators while two Grey Vats pump out robots. Legend: see level1.js. */
export const level2 = {
  id: '1-2',
  title: 'Tram Yards',
  place: 'Purrville · Hue Line Depot',
  theme: 'yard',
  beaconName: 'Depot Beacon',
  map: [
    '####################################',
    '#S....#####.........#######.....g..#',
    '#.....#####...d.....#######........#',
    '#..N..#####....B....#######..V.....#',
    '#..................................#',
    '#==================================#',
    '#.......f.....L.........L......*...#',
    '#.g...........................m....#',
    '#######....#########....############',
    '#######....#########....############',
    '#.h...d....#########....#....*.....#',
    '#==================================#',
    '#..........f.........V.............#',
    '#....B.........L..........B.....g..#',
    '######....##########.......#WWWWWWW#',
    '#.g........................#.......#',
    '#==========================#.......#',
    '#.....d.......*.........m..#...E...#',
    '#....B.........f...........#.......#',
    '#..L.......L.......L.......#.......#',
    '#..........................#.......#',
    '####################################',
  ],
  stages: [{ tasks: ['generators', 'vats'] }],
  vatPattern: ['drab', 'drab', 'fizz', 'drab', 'mopper', 'drab', 'fizz'],
  beaconChargeTime: 28,
  npcs: [
    {
      id: 'mittens', name: 'Conductor Mittens', model: 'mittens',
      lines: [
        ['Conductor Mittens', 'Courier! The Greyscale shut down all four tram generators.'],
        ['Conductor Mittens', "Stand next to each one until it hums. And take these Paint Bombs. They were meant for the festival fireworks."],
      ],
      reward: { items: { bomb: 3 } }, rewardText: '+3 Paint Bombs',
      after: [['Conductor Mittens', 'Press G to throw a Paint Bomb where you aim. Mind your whiskers!']],
    },
  ],
  lines: {
    intro: [
      ['Nova', 'The Tram Yards. Every line in Purrville starts here.'],
      ['Smudge', 'Beep-boop. (four blinking dots appear on the minimap)'],
      ['Nova', 'Four generators, two Grey Vats. Easy. Probably.'],
    ],
    gens_1: [['Nova', 'One generator humming!']],
    gens_2: [['Smudge', 'Beep! (two of four)']],
    gens_3: [['Nova', 'One more generator!']],
    vats_1: [['Nova', 'One Vat down. One to go.']],
    stageClear: [
      ['Nova', 'Generators online, Vats popped. The depot barrier is open!'],
      ['Smudge', 'Beep! (it points southeast)'],
    ],
    beaconStart: [
      ['Nova', 'Depot Beacon, wake up!'],
      ['Nova', 'Here comes the night shift. Hold on!'],
    ],
    lowHealth: [['Smudge', 'Beep! (press H for sardines!)']],
    beaconDone: [['Nova', 'Next stop: everywhere!']],
  },
};
